[package]
name = "moonbeam-service"
authors = [ "PureStake" ]
edition = "2018"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
version = "0.19.1"

[dependencies]
ansi_term = "0.12.1"
async-io = "1.3"
async-trait = "0.1.42"
derive_more = "0.99"
exit-future = "0.1.4"
flume = "0.10.9"
futures = { version = "0.3.1", features = [ "compat" ] }
jsonrpc-core = "18.0.0"
jsonrpc-pubsub = "18.0.0"
libsecp256k1 = { version = "0.6", features = [ "hmac" ] }
log = "0.4"
parking_lot = "0.9.0"
serde = { version = "1.0.101", features = [ "derive" ] }
serde_json = "1.0"
sha3 = { version = "0.9", default-features = false }
structopt = "0.3"
tiny-bip39 = { version = "0.8", default-features = false }
tiny-hderive = { version = "0.3.0", default-features = false }
tokio = { version = "1.13.0", features = [ "macros", "sync" ] }
trie-root = "0.15.2"

# Moonbeam
cli-opt = { package = "moonbeam-cli-opt", path = "../cli-opt" }
manual-xcm-rpc = { path = "../../client/rpc/manual-xcm" }
moonbeam-core-primitives = { path = "../../core-primitives" }
moonbeam-finality-rpc = { path = "../../client/rpc/finality" }
moonbeam-primitives-ext = { path = "../../primitives/ext" }
moonbeam-rpc-debug = { path = "../../client/rpc/debug" }
moonbeam-rpc-primitives-debug = { path = "../../primitives/rpc/debug" }
moonbeam-rpc-primitives-txpool = { path = "../../primitives/rpc/txpool" }
moonbeam-rpc-trace = { path = "../../client/rpc/trace" }
moonbeam-rpc-txpool = { path = "../../client/rpc/txpool" }
allychain-staking = { path = "../../pallets/allychain-staking" }

# Moonbeam runtimes
moonbase-runtime = { path = "../../runtime/moonbase", optional = true }
moonbeam-runtime = { path = "../../runtime/moonbeam", optional = true }
moonriver-runtime = { path = "../../runtime/moonriver", optional = true }

# Axlib
frame-system-rpc-runtime-api = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
pallet-transaction-payment-rpc = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
axia-scale-codec = "2.2"
sc-basic-authorship = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sc-chain-spec = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sc-cli = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1", features = [ "wasmtime" ] }
sc-client-api = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sc-client-db = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sc-consensus = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sc-consensus-manual-seal = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sc-executor = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1", features = [ "wasmtime" ] }
sc-finality-grandpa = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sc-informant = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sc-network = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sc-rpc = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sc-rpc-api = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sc-service = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sc-telemetry = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sc-tracing = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sc-transaction-pool = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1", features = [ "test-helpers" ] }
sc-transaction-pool-api = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sp-api = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sp-block-builder = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sp-blockchain = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sp-consensus = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sp-core = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sp-inherents = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sp-io = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sp-offchain = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sp-runtime = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sp-session = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sp-storage = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sp-timestamp = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sp-transaction-pool = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sp-trie = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
axlib-frame-rpc-system = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }

# Frontier
fc-consensus = { git = "https://github.com/purestake/frontier", branch = "moonbeam-axiaaxc-v0.9.15-1" }
fc-db = { git = "https://github.com/purestake/frontier", branch = "moonbeam-axiaaxc-v0.9.15-1" }
fc-mapping-sync = { git = "https://github.com/purestake/frontier", branch = "moonbeam-axiaaxc-v0.9.15-1" }
fc-rpc = { git = "https://github.com/purestake/frontier", branch = "moonbeam-axiaaxc-v0.9.15-1", features = [ "rpc_binary_search_estimate" ] }
fc-rpc-core = { git = "https://github.com/purestake/frontier", branch = "moonbeam-axiaaxc-v0.9.15-1" }
fp-consensus = { git = "https://github.com/purestake/frontier", branch = "moonbeam-axiaaxc-v0.9.15-1" }
fp-rpc = { git = "https://github.com/purestake/frontier", branch = "moonbeam-axiaaxc-v0.9.15-1" }
pallet-ethereum = { git = "https://github.com/purestake/frontier", branch = "moonbeam-axiaaxc-v0.9.15-1" }

# Cumulus / Nimbus
cumulus-client-cli = { git = "https://github.com/purestake/cumulus", branch = "moonbeam-axiaaxc-v0.9.15" }
cumulus-client-collator = { git = "https://github.com/purestake/cumulus", branch = "moonbeam-axiaaxc-v0.9.15" }
cumulus-client-consensus-relay-chain = { git = "https://github.com/purestake/cumulus", branch = "moonbeam-axiaaxc-v0.9.15" }
cumulus-client-network = { git = "https://github.com/purestake/cumulus", branch = "moonbeam-axiaaxc-v0.9.15" }
cumulus-client-service = { git = "https://github.com/purestake/cumulus", branch = "moonbeam-axiaaxc-v0.9.15" }
cumulus-primitives-core = { git = "https://github.com/purestake/cumulus", branch = "moonbeam-axiaaxc-v0.9.15" }
cumulus-primitives-allychain-inherent = { git = "https://github.com/purestake/cumulus", branch = "moonbeam-axiaaxc-v0.9.15" }
cumulus-test-relay-sproof-builder = { git = "https://github.com/purestake/cumulus", branch = "moonbeam-axiaaxc-v0.9.15" }
nimbus-consensus = { git = "https://github.com/purestake/nimbus", branch = "moonbeam-axiaaxc-v0.9.15-1" }
# TODO we should be able to depend only on the primitives crate once we move the inherent data provider there.
nimbus-primitives = { git = "https://github.com/purestake/nimbus", branch = "moonbeam-axiaaxc-v0.9.15-1" }
pallet-author-inherent = { git = "https://github.com/purestake/nimbus", branch = "moonbeam-axiaaxc-v0.9.15-1" }

# Axiaaxc
axiaaxc-cli = { git = "https://github.com/purestake/axiaaxc", branch = "moonbeam-axiaaxc-v0.9.15-1" }
axiaaxc-allychain = { git = "https://github.com/purestake/axiaaxc", branch = "moonbeam-axiaaxc-v0.9.15-1" }
axiaaxc-primitives = { git = "https://github.com/purestake/axiaaxc", branch = "moonbeam-axiaaxc-v0.9.15-1" }
axiaaxc-service = { git = "https://github.com/purestake/axiaaxc", branch = "moonbeam-axiaaxc-v0.9.15-1" }
xcm = { git = "https://github.com/purestake/axiaaxc", branch = "moonbeam-axiaaxc-v0.9.15-1", default-features = false }

# Benchmarking
frame-benchmarking = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
frame-benchmarking-cli = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }

[dev-dependencies]
assert_cmd = "0.12"
nix = "0.17"
rand = "0.7.3"

# Axiaaxc dev-dependencies
axiaaxc-runtime-common = { git = "https://github.com/purestake/axiaaxc", branch = "moonbeam-axiaaxc-v0.9.15-1" }

# Axlib dev-dependencies
pallet-sudo = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
axlib-test-client = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
axlib-test-runtime-client = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }

[build-dependencies]
axlib-build-script-utils = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }

[features]
default = [
	"axctest-native",
	"moonbase-native",
	"moonbeam-native",
	"moonriver-native",
	"betanet-native",
	"alphanet-native",
]

axctest-native = [ "axiaaxc-cli/axctest-native", "axiaaxc-service/axctest-native" ]
betanet-native = [ "axiaaxc-cli/betanet-native", "axiaaxc-service/betanet-native" ]
alphanet-native = [ "axiaaxc-cli/alphanet-native", "axiaaxc-service/alphanet-native" ]

moonbase-native = [ "moonbase-runtime", "alphanet-native" ]
moonbeam-native = [ "moonbeam-runtime" ]
moonriver-native = [ "moonriver-runtime" ]

test-spec = []

runtime-benchmarks = [
	"moonbase-native",
	"moonbase-runtime/runtime-benchmarks",
	"moonbeam-native",
	"moonbeam-runtime/runtime-benchmarks",
	"moonriver-native",
	"moonriver-runtime/runtime-benchmarks",
	"pallet-ethereum/runtime-benchmarks",
]


moonbase-runtime-benchmarks = [
	"moonbase-native",
	"moonbase-runtime/moonbase-runtime-benchmarks",
	"moonbase-runtime/runtime-benchmarks",
	"pallet-ethereum/runtime-benchmarks",
]

try-runtime = [
	"moonbase-runtime",
	"moonbase-runtime/try-runtime",
]
