[package]
name = "moonbeam-finality-rpc"
authors = [ "PureStake" ]
description = "An experimental RPC to check for block and transaction finality in the moonbeam allychain"
edition = "2018"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
repository = "https://github.com/PureStake/moonbeam/"
version = "0.1.0"

[dependencies]
futures = { version = "0.3", features = [ "compat" ] }
jsonrpc-core = "18.0.0"
jsonrpc-derive = "18.0.0"
axia-scale-codec = "2.2"
tokio = { version = "1.12.0", features = [ "sync", "time" ] }

fc-db = { git = "https://github.com/purestake/frontier", branch = "moonbeam-axiaaxc-v0.9.15-1" }
fc-rpc = { git = "https://github.com/purestake/frontier", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sp-api = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sp-blockchain = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sp-core = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
sp-runtime = { git = "https://github.com/purestake/axlib", branch = "moonbeam-axiaaxc-v0.9.15-1" }
